/*
 * This file is generated by jOOQ.
 */
package D6.Entities.routines;


import D6.Entities.Bookings;

import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Lang extends AbstractRoutine<String> {

    private static final long serialVersionUID = 1L;

    /**
     * The parameter <code>bookings.lang.RETURN_VALUE</code>.
     */
    public static final Parameter<String> RETURN_VALUE = Internal.createParameter("RETURN_VALUE", SQLDataType.CLOB, false, false);

    /**
     * Create a new routine call instance
     */
    public Lang() {
        super("lang", Bookings.BOOKINGS, SQLDataType.CLOB);

        setReturnParameter(RETURN_VALUE);
    }
}
