/*
 * This file is generated by jOOQ.
 */
package D6.Entities.tables.records;


import D6.Entities.tables.AircraftsData;

import org.jooq.Field;
import org.jooq.JSONB;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * Aircrafts (internal data)
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AircraftsDataRecord extends UpdatableRecordImpl<AircraftsDataRecord> implements Record3<String, JSONB, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>bookings.aircrafts_data.aircraft_code</code>. Aircraft
     * code, IATA
     */
    public void setAircraftCode(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>bookings.aircrafts_data.aircraft_code</code>. Aircraft
     * code, IATA
     */
    public String getAircraftCode() {
        return (String) get(0);
    }

    /**
     * Setter for <code>bookings.aircrafts_data.model</code>. Aircraft model
     */
    public void setModel(JSONB value) {
        set(1, value);
    }

    /**
     * Getter for <code>bookings.aircrafts_data.model</code>. Aircraft model
     */
    public JSONB getModel() {
        return (JSONB) get(1);
    }

    /**
     * Setter for <code>bookings.aircrafts_data.range</code>. Maximal flying
     * distance, km
     */
    public void setRange(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>bookings.aircrafts_data.range</code>. Maximal flying
     * distance, km
     */
    public Integer getRange() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<String, JSONB, Integer> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<String, JSONB, Integer> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return AircraftsData.AIRCRAFTS_DATA.AIRCRAFT_CODE;
    }

    @Override
    public Field<JSONB> field2() {
        return AircraftsData.AIRCRAFTS_DATA.MODEL;
    }

    @Override
    public Field<Integer> field3() {
        return AircraftsData.AIRCRAFTS_DATA.RANGE;
    }

    @Override
    public String component1() {
        return getAircraftCode();
    }

    @Override
    public JSONB component2() {
        return getModel();
    }

    @Override
    public Integer component3() {
        return getRange();
    }

    @Override
    public String value1() {
        return getAircraftCode();
    }

    @Override
    public JSONB value2() {
        return getModel();
    }

    @Override
    public Integer value3() {
        return getRange();
    }

    @Override
    public AircraftsDataRecord value1(String value) {
        setAircraftCode(value);
        return this;
    }

    @Override
    public AircraftsDataRecord value2(JSONB value) {
        setModel(value);
        return this;
    }

    @Override
    public AircraftsDataRecord value3(Integer value) {
        setRange(value);
        return this;
    }

    @Override
    public AircraftsDataRecord values(String value1, JSONB value2, Integer value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AircraftsDataRecord
     */
    public AircraftsDataRecord() {
        super(AircraftsData.AIRCRAFTS_DATA);
    }

    /**
     * Create a detached, initialised AircraftsDataRecord
     */
    public AircraftsDataRecord(String aircraftCode, JSONB model, Integer range) {
        super(AircraftsData.AIRCRAFTS_DATA);

        setAircraftCode(aircraftCode);
        setModel(model);
        setRange(range);
    }
}
