/*
 * This file is generated by jOOQ.
 */
package D6.Entities.tables.records;


import D6.Entities.tables.AirportsData;

import org.jooq.Field;
import org.jooq.JSONB;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * Airports (internal data)
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AirportsDataRecord extends UpdatableRecordImpl<AirportsDataRecord> implements Record5<String, JSONB, JSONB, Object, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>bookings.airports_data.airport_code</code>. Airport code
     */
    public void setAirportCode(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>bookings.airports_data.airport_code</code>. Airport code
     */
    public String getAirportCode() {
        return (String) get(0);
    }

    /**
     * Setter for <code>bookings.airports_data.airport_name</code>. Airport name
     */
    public void setAirportName(JSONB value) {
        set(1, value);
    }

    /**
     * Getter for <code>bookings.airports_data.airport_name</code>. Airport name
     */
    public JSONB getAirportName() {
        return (JSONB) get(1);
    }

    /**
     * Setter for <code>bookings.airports_data.city</code>. City
     */
    public void setCity(JSONB value) {
        set(2, value);
    }

    /**
     * Getter for <code>bookings.airports_data.city</code>. City
     */
    public JSONB getCity() {
        return (JSONB) get(2);
    }

    /**
     * @deprecated Unknown data type. If this is a qualified, user-defined type,
     * it may have been excluded from code generation. If this is a built-in
     * type, you can define an explicit {@link org.jooq.Binding} to specify how
     * this type should be handled. Deprecation can be turned off using
     * {@literal <deprecationOnUnknownTypes/>} in your code generator
     * configuration.
     */
    @Deprecated
    public void setCoordinates(Object value) {
        set(3, value);
    }

    /**
     * @deprecated Unknown data type. If this is a qualified, user-defined type,
     * it may have been excluded from code generation. If this is a built-in
     * type, you can define an explicit {@link org.jooq.Binding} to specify how
     * this type should be handled. Deprecation can be turned off using
     * {@literal <deprecationOnUnknownTypes/>} in your code generator
     * configuration.
     */
    @Deprecated
    public Object getCoordinates() {
        return get(3);
    }

    /**
     * Setter for <code>bookings.airports_data.timezone</code>. Airport time
     * zone
     */
    public void setTimezone(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>bookings.airports_data.timezone</code>. Airport time
     * zone
     */
    public String getTimezone() {
        return (String) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<String, JSONB, JSONB, Object, String> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<String, JSONB, JSONB, Object, String> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return AirportsData.AIRPORTS_DATA.AIRPORT_CODE;
    }

    @Override
    public Field<JSONB> field2() {
        return AirportsData.AIRPORTS_DATA.AIRPORT_NAME;
    }

    @Override
    public Field<JSONB> field3() {
        return AirportsData.AIRPORTS_DATA.CITY;
    }

    /**
     * @deprecated Unknown data type. If this is a qualified, user-defined type,
     * it may have been excluded from code generation. If this is a built-in
     * type, you can define an explicit {@link org.jooq.Binding} to specify how
     * this type should be handled. Deprecation can be turned off using
     * {@literal <deprecationOnUnknownTypes/>} in your code generator
     * configuration.
     */
    @Deprecated
    @Override
    public Field<Object> field4() {
        return AirportsData.AIRPORTS_DATA.COORDINATES;
    }

    @Override
    public Field<String> field5() {
        return AirportsData.AIRPORTS_DATA.TIMEZONE;
    }

    @Override
    public String component1() {
        return getAirportCode();
    }

    @Override
    public JSONB component2() {
        return getAirportName();
    }

    @Override
    public JSONB component3() {
        return getCity();
    }

    /**
     * @deprecated Unknown data type. If this is a qualified, user-defined type,
     * it may have been excluded from code generation. If this is a built-in
     * type, you can define an explicit {@link org.jooq.Binding} to specify how
     * this type should be handled. Deprecation can be turned off using
     * {@literal <deprecationOnUnknownTypes/>} in your code generator
     * configuration.
     */
    @Deprecated
    @Override
    public Object component4() {
        return getCoordinates();
    }

    @Override
    public String component5() {
        return getTimezone();
    }

    @Override
    public String value1() {
        return getAirportCode();
    }

    @Override
    public JSONB value2() {
        return getAirportName();
    }

    @Override
    public JSONB value3() {
        return getCity();
    }

    /**
     * @deprecated Unknown data type. If this is a qualified, user-defined type,
     * it may have been excluded from code generation. If this is a built-in
     * type, you can define an explicit {@link org.jooq.Binding} to specify how
     * this type should be handled. Deprecation can be turned off using
     * {@literal <deprecationOnUnknownTypes/>} in your code generator
     * configuration.
     */
    @Deprecated
    @Override
    public Object value4() {
        return getCoordinates();
    }

    @Override
    public String value5() {
        return getTimezone();
    }

    @Override
    public AirportsDataRecord value1(String value) {
        setAirportCode(value);
        return this;
    }

    @Override
    public AirportsDataRecord value2(JSONB value) {
        setAirportName(value);
        return this;
    }

    @Override
    public AirportsDataRecord value3(JSONB value) {
        setCity(value);
        return this;
    }

    /**
     * @deprecated Unknown data type. If this is a qualified, user-defined type,
     * it may have been excluded from code generation. If this is a built-in
     * type, you can define an explicit {@link org.jooq.Binding} to specify how
     * this type should be handled. Deprecation can be turned off using
     * {@literal <deprecationOnUnknownTypes/>} in your code generator
     * configuration.
     */
    @Deprecated
    @Override
    public AirportsDataRecord value4(Object value) {
        setCoordinates(value);
        return this;
    }

    @Override
    public AirportsDataRecord value5(String value) {
        setTimezone(value);
        return this;
    }

    @Override
    public AirportsDataRecord values(String value1, JSONB value2, JSONB value3, Object value4, String value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AirportsDataRecord
     */
    public AirportsDataRecord() {
        super(AirportsData.AIRPORTS_DATA);
    }

    /**
     * Create a detached, initialised AirportsDataRecord
     */
    public AirportsDataRecord(String airportCode, JSONB airportName, JSONB city, Object coordinates, String timezone) {
        super(AirportsData.AIRPORTS_DATA);

        setAirportCode(airportCode);
        setAirportName(airportName);
        setCity(city);
        setCoordinates(coordinates);
        setTimezone(timezone);
    }
}
