/*
 * This file is generated by jOOQ.
 */
package D6.Entities;


import D6.Entities.tables.Aircrafts;
import D6.Entities.tables.AircraftsData;
import D6.Entities.tables.Airports;
import D6.Entities.tables.AirportsData;
import D6.Entities.tables.BoardingPasses;
import D6.Entities.tables.Bookings;
import D6.Entities.tables.Flights;
import D6.Entities.tables.FlightsV;
import D6.Entities.tables.Routes;
import D6.Entities.tables.Seats;
import D6.Entities.tables.TicketFlights;
import D6.Entities.tables.Tickets;


/**
 * Convenience access to all tables in bookings.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * Aircrafts
     */
    public static final Aircrafts AIRCRAFTS = Aircrafts.AIRCRAFTS;

    /**
     * Aircrafts (internal data)
     */
    public static final AircraftsData AIRCRAFTS_DATA = AircraftsData.AIRCRAFTS_DATA;

    /**
     * Airports
     */
    public static final Airports AIRPORTS = Airports.AIRPORTS;

    /**
     * Airports (internal data)
     */
    public static final AirportsData AIRPORTS_DATA = AirportsData.AIRPORTS_DATA;

    /**
     * Boarding passes
     */
    public static final BoardingPasses BOARDING_PASSES = BoardingPasses.BOARDING_PASSES;

    /**
     * Bookings
     */
    public static final Bookings BOOKINGS_ = Bookings.BOOKINGS_;

    /**
     * Flights
     */
    public static final Flights FLIGHTS = Flights.FLIGHTS;

    /**
     * Flights (extended)
     */
    public static final FlightsV FLIGHTS_V = FlightsV.FLIGHTS_V;

    /**
     * Routes
     */
    public static final Routes ROUTES = Routes.ROUTES;

    /**
     * Seats
     */
    public static final Seats SEATS = Seats.SEATS;

    /**
     * Flight segment
     */
    public static final TicketFlights TICKET_FLIGHTS = TicketFlights.TICKET_FLIGHTS;

    /**
     * Tickets
     */
    public static final Tickets TICKETS = Tickets.TICKETS;
}
