/*
 * This file is generated by jOOQ.
 */
package D6.Entities.tables;


import D6.Entities.Bookings;
import D6.Entities.tables.records.AircraftsRecord;

import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function3;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row3;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * Aircrafts
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Aircrafts extends TableImpl<AircraftsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>bookings.aircrafts</code>
     */
    public static final Aircrafts AIRCRAFTS = new Aircrafts();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AircraftsRecord> getRecordType() {
        return AircraftsRecord.class;
    }

    /**
     * The column <code>bookings.aircrafts.aircraft_code</code>. Aircraft code,
     * IATA
     */
    public final TableField<AircraftsRecord, String> AIRCRAFT_CODE = createField(DSL.name("aircraft_code"), SQLDataType.CHAR(3), this, "Aircraft code, IATA");

    /**
     * The column <code>bookings.aircrafts.model</code>. Aircraft model
     */
    public final TableField<AircraftsRecord, String> MODEL = createField(DSL.name("model"), SQLDataType.CLOB, this, "Aircraft model");

    /**
     * The column <code>bookings.aircrafts.range</code>. Maximal flying
     * distance, km
     */
    public final TableField<AircraftsRecord, Integer> RANGE = createField(DSL.name("range"), SQLDataType.INTEGER, this, "Maximal flying distance, km");

    private Aircrafts(Name alias, Table<AircraftsRecord> aliased) {
        this(alias, aliased, null);
    }

    private Aircrafts(Name alias, Table<AircraftsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment("Aircrafts"), TableOptions.view("""
        create view "aircrafts" as  SELECT ml.aircraft_code,
         (ml.model ->> lang()) AS model,
         ml.range
        FROM aircrafts_data ml;
        """));
    }

    /**
     * Create an aliased <code>bookings.aircrafts</code> table reference
     */
    public Aircrafts(String alias) {
        this(DSL.name(alias), AIRCRAFTS);
    }

    /**
     * Create an aliased <code>bookings.aircrafts</code> table reference
     */
    public Aircrafts(Name alias) {
        this(alias, AIRCRAFTS);
    }

    /**
     * Create a <code>bookings.aircrafts</code> table reference
     */
    public Aircrafts() {
        this(DSL.name("aircrafts"), null);
    }

    public <O extends Record> Aircrafts(Table<O> child, ForeignKey<O, AircraftsRecord> key) {
        super(child, key, AIRCRAFTS);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Bookings.BOOKINGS;
    }

    @Override
    public Aircrafts as(String alias) {
        return new Aircrafts(DSL.name(alias), this);
    }

    @Override
    public Aircrafts as(Name alias) {
        return new Aircrafts(alias, this);
    }

    @Override
    public Aircrafts as(Table<?> alias) {
        return new Aircrafts(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Aircrafts rename(String name) {
        return new Aircrafts(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Aircrafts rename(Name name) {
        return new Aircrafts(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Aircrafts rename(Table<?> name) {
        return new Aircrafts(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row3<String, String, Integer> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function3<? super String, ? super String, ? super Integer, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function3<? super String, ? super String, ? super Integer, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
